"""empty message

Revision ID: 0d4aa50569ba
Revises: 3e0c92f33945
Create Date: 2021-11-09 22:33:23.847940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4aa50569ba'
down_revision = '3e0c92f33945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('myuser', 'email',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('myuser', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###
