"""Show error

Revision ID: 405483de04ec
Revises: 851c67e906f4
Create Date: 2021-11-07 11:13:31.669521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405483de04ec'
down_revision = '851c67e906f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myuser',
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('create_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('myuser')
    # ### end Alembic commands ###
