"""empty message

Revision ID: b2fe13b9ff52
Revises: 
Create Date: 2021-12-05 11:51:03.302013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2fe13b9ff52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('pay', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_name'), 'simple', ['name'], unique=True)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['simple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prices')
    op.drop_table('park')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('park',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('get_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('get_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tax', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pay', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='park_pkey')
    )
    op.create_table('prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stay_time', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='prices_pkey')
    )
    op.drop_table('transaction')
    op.drop_index(op.f('ix_simple_name'), table_name='simple')
    op.drop_table('simple')
    # ### end Alembic commands ###
